// gohafas wraps the autogenerated openapi client provided by vbbraw which was
// generated from https://vbb-demo.demo2.hafas.cloud/api/fahrinfo/latest/api-doc via the flake.nix file at the root of this project
package gohafas
